In [1]:
import pandas as pd

df = pd.read_csv("../data/people_diabetes.csv")

df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [1]:
df.isna

NameError: name 'df' is not defined

In [2]:
pd.info()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/people_diabetes.csv")

In [15]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [3]:
df.info()

NameError: name 'df' is not defined

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [17]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [4]:
import pandas as pd

In [18]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.isna

<bound method DataFrame.isna of       Name  Age Gender  Glucose  BloodPressure   BMI  Insulin  \
0    Ahmed   45      M    148.0             72  33.6      0.0
1      Ali   32      M     85.0             66  26.6     94.0
2     Sara   28      F     89.0             66  28.1     94.0
3   Fatima   52      F    183.0             64  23.3      0.0
4    Usman   41      M    137.0             40  43.1    168.0
5   Ayesha   35      F    116.0             74  34.0      0.0
6    Bilal   29      M     78.0             50  31.0     88.0
7     Hina   60      F    126.0             88  39.3      0.0
8     Omar   48      M    180.0             90  42.0    200.0
9   Zainab   31      F    100.0             72  25.5     90.0
10   Hamza   55      M    195.0             92  36.5      0.0
11  Mariam   38      F    110.0             70  32.0      NaN
12  Kashif   44      M      NaN             80  35.2    150.0
13    Sana   27      F     92.0             68  24.8     85.0
14   Imran   50      M    160.0             85  38.0    175.0
15   Nadia   42      F    105.0             75  29.5    120.0
16  Farhan   36      M     99.0             70  27.2    100.0
17   Lubna   58      F    170.0             95  45.0    300.0
18   Tariq   46      M    130.0             78  31.5    140.0
19   Sadia   33      F     88.0             60  22.5     80.0
20   Ahmed   45      M    148.0             72  33.6      0.0
21  Rashid   39      M    250.0            110  55.0    400.0

    DiabetesPedigree  Outcome
0              0.627        1
1              0.351        0
2              0.167        0
3              0.672        1
4              2.288        1
5              0.188        0
6              0.248        0
7              0.704        0
8              1.200        1
9              0.250        0
10             0.900        1
11             0.300        0
12             0.450        1
13             0.180        0
14             0.850        1
15             0.250        0
16             0.300        0
17             1.100        1
18             0.500        1
19             0.150        0
20             0.627        1
21             1.500        1  >

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
In [1]:
import pandas as pd

SyntaxError: invalid syntax (3369233704.py, line 1)

In [20]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [6]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [21]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
import pandas as pd

In [22]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [23]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [25]:
missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Percentage":(df.isnull().sum() / len(df)*100).round(2)
})

In [26]:
missing

             Missing  Percentage
PassengerId        0        0.00
Survived           0        0.00
Pclass             0        0.00
Name               0        0.00
Sex                0        0.00
Age              177       19.87
SibSp              0        0.00
Parch              0        0.00
Ticket             0        0.00
Fare               0        0.00
Cabin            687       77.10
Embarked           2        0.22

In [7]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import csv
from pathlib import Path
from math import log

ModuleNotFoundError: No module named 'matplotlib'

In [14]:
from pathlib import Path

In [13]:
import csv

In [12]:
import matplotlib.pyplot as plt

In [11]:
import matplotlib

In [10]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'

In [9]:
import numpy as np

In [8]:
import pandas as pd

In [8]:
df = pd.read_csv("../data/people_diabetes.csv")

In [1]:
import pandas as pd

In [9]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [3]:
df = pd.read_csv("../data/people_diabetes.csv")

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              22 non-null     str
 1   Age               22 non-null     int64
 2   Gender            22 non-null     str
 3   Glucose           21 non-null     float64
 4   BloodPressure     22 non-null     int64
 5   BMI               22 non-null     float64
 6   Insulin           21 non-null     float64
 7   DiabetesPedigree  22 non-null     float64
 8   Outcome           22 non-null     int64
dtypes: float64(4), int64(3), str(2)
memory usage: 1.7 KB

In [4]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [11]:
df["Outcome"].value_counts()

Outcome
1    11
0    11
Name: count, dtype: int64

In [12]:
df[df["Glucose"] > 140]

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1