In [1]:
import pandas as pd

df = pd.read_csv("../data/people_diabetes.csv")

df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [1]:

import pandas as pd

# 1. Create a Series with student names and scores
student_scores = pd.Series(
    [36, 73, 56, 66, 87],
    index=["Mary", "Jack", "Ahmed", "June", "Hassan"],
    name="Student Scores"
)

# 2. Display the Series
print("Student Scores:")
print(student_scores)

# 3. Retrieve Ahmed's score using .loc
print("\nAhmed's score:", student_scores.loc["Ahmed"])

# 4. Find the highest score using .max()
print("Highest score:", student_scores.max())

# 5. Calculate the mean score
print("Mean score:", student_scores.mean())

# 6. List students who scored 60 or above
print("\nStudents scoring 60 or above:")
print(student_scores[student_scores >= 60])

Student Scores:
Mary      36
Jack      73
Ahmed     56
June      66
Hassan    87
Name: Student Scores, dtype: int64

Ahmed's score: 56
Highest score: 87
Mean score: 63.6

Students scoring 60 or above:
Jack      73
June      66
Hassan    87
Name: Student Scores, dtype: int64

In [1]:

import pandas as pd

# 1. Read the CSV file into a DataFrame
df = pd.read_csv("students.csv")

# 2. Display the first five rows
print("First five rows:")
print(df.head())

# 3. Display DataFrame information
print("\nDataFrame information:")
df.info()

# 4. Display summary statistics
print("\nSummary statistics:")
print(df.describe())

FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'

In [2]:

import pandas as pd

# 1. Create a DataFrame with student names and scores
data = {
    "Name": ["Mary", "Jack", "Ahmed", "June", "Hassan"],
    "Score": [36, 73, 56, 66, 87]
}

df = pd.DataFrame(data)

print("Original Student DataFrame:")
print(df)

# 2. Add a Rank column (highest score gets rank 1)
df["Rank"] = df["Score"].rank(
    ascending=False,
    method="min"
).astype(int)

print("\nDataFrame with Ranks:")
print(df)

# 3. Sort by Score in descending order
sorted_df = df.sort_values(
    by="Score",
    ascending=False
)

print("\nStudents Sorted by Score:")
print(sorted_df[["Name", "Score", "Rank"]])

# 4. Filter students with a score of at least 60
top_students = sorted_df[sorted_df["Score"] >= 60]

print("\nStudents Scoring 60 or Above:")
print(top_students[["Name", "Score", "Rank"]])

Original Student DataFrame:
     Name  Score
0    Mary     36
1    Jack     73
2   Ahmed     56
3    June     66
4  Hassan     87

DataFrame with Ranks:
     Name  Score  Rank
0    Mary     36     5
1    Jack     73     2
2   Ahmed     56     4
3    June     66     3
4  Hassan     87     1

Students Sorted by Score:
     Name  Score  Rank
4  Hassan     87     1
1    Jack     73     2
3    June     66     3
2   Ahmed     56     4
0    Mary     36     5

Students Scoring 60 or Above:
     Name  Score  Rank
4  Hassan     87     1
1    Jack     73     2
3    June     66     3

In [3]:

import pandas as pd
import numpy as np

# Create a DataFrame with missing values
df = pd.DataFrame({
    "A": [1, 2, np.nan, 4],
    "B": [np.nan, 3, np.nan, 5],
    "C": [6, 7, 8, 9]
})

# Create a report of missing values
report = pd.DataFrame({
    "Missing": df.isna().sum(),
    "Percent": (df.isna().mean() * 100).round(1)
})

# Display the report
print(report)

   Missing  Percent
A        1     25.0
B        2     50.0
C        0      0.0

In [4]:

import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values
df = pd.DataFrame({
    "Name": ["Mary", "Jack", "Ahmed", "June", "Hassan"],
    "Score": [36, 73, np.nan, 66, 87],
    "Age": [22, np.nan, 25, 23, 24]
})

# Check the original data
print("Original DataFrame:")
print(df)

print("\nMissing values before cleaning:")
print(df.isna().sum())

# Clean the data by removing rows with missing values
df_clean = df.dropna()

# Check the cleaned data
print("\nCleaned DataFrame:")
print(df_clean)

print("\nMissing values after cleaning:")
print(df_clean.isna().sum())

# Compare the number of rows before and after cleaning
print("\nRows before cleaning:", len(df))
print("Rows after cleaning:", len(df_clean))

Original DataFrame:
     Name  Score   Age
0    Mary   36.0  22.0
1    Jack   73.0   NaN
2   Ahmed    NaN  25.0
3    June   66.0  23.0
4  Hassan   87.0  24.0

Missing values before cleaning:
Name     0
Score    1
Age      1
dtype: int64

Cleaned DataFrame:
     Name  Score   Age
0    Mary   36.0  22.0
3    June   66.0  23.0
4  Hassan   87.0  24.0

Missing values after cleaning:
Name     0
Score    0
Age      0
dtype: int64

Rows before cleaning: 5
Rows after cleaning: 3

In [2]:

import numpy as np

angles_deg = np.array([0, 30, 45, 60, 90])

# Convert degrees to radians
angles_rad = np.deg2rad(angles_deg)

# Calculate sine and cosine
s = np.sin(angles_rad)
c = np.cos(angles_rad)

print(np.round(s, 3))
print(np.round(c, 3))
print(np.hypot(5, 2))

[0.    0.5   0.707 0.866 1.   ]
[1.    0.866 0.707 0.5   0.   ]
5.385164807134504

In [3]:

import numpy as np

degrees = np.array([30., 150.])

s = np.sin(np.deg2rad(degrees))
recovered = np.rad2deg(np.arcsin(s))

print(np.round(recovered))

x = np.array([0., 1.])
print(np.allclose(np.arccosh(np.cosh(x)), x))

[30. 30.]
True

In [4]:

import numpy as np

weight = np.array([48.2, 52, 56, 58,
                   51.3, 65.6, 47.1, 49])

print(np.min(weight), np.max(weight))
print(np.ptp(weight))
print(np.mean(weight))
print(np.median(weight))
print(np.percentile(weight, 70))

47.1 65.6
18.499999999999993
53.4
51.65
55.599999999999994

In [5]:

import numpy as np

X = np.array([[10, 20],
              [30, 40],
              [50, 60]])

print(np.mean(X, axis=0))
print(np.sum(X, axis=1))
print(np.mean(X, axis=0).shape)
print(np.sum(X, axis=1).shape)

[30. 40.]
[ 30  70 110]
(2,)
(3,)

In [6]:

import numpy as np

# Example 1: Typical data
scores = np.array([5, 6, 7, 8, 9])

print("Typical data:", scores)
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))

print("--------------------")

# Example 2: Data with an outlier
scores_outlier = np.array([5, 6, 7, 8, 100])

print("Data with outlier:", scores_outlier)
print("Mean:", np.mean(scores_outlier))
print("Median:", np.median(scores_outlier))

Typical data: [5 6 7 8 9]
Mean: 7.0
Median: 7.0
--------------------
Data with outlier: [  5   6   7   8 100]
Mean: 25.2
Median: 7.0

In [7]:

import numpy as np

# Example 1: Typical data
scores = np.array([5, 6, 7, 8, 9], dtype=float)

print("=== Typical Data ===")
print("Scores:", scores)
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))

# Z-score formula: z = (x - mean) / standard deviation
mean = np.mean(scores)
std = np.std(scores)  # Population standard deviation
z_scores = (scores - mean) / std

print("Standard deviation:", round(std, 2))
print("Z-scores:", np.round(z_scores, 2))
print("Potential outliers:", scores[np.abs(z_scores) > 3])

print("\n=== Data With an Outlier ===")

# Example 2: Add an extreme value
scores_outlier = np.array([5, 6, 7, 8, 100], dtype=float)

print("Scores:", scores_outlier)
print("Mean:", np.mean(scores_outlier))
print("Median:", np.median(scores_outlier))

mean2 = np.mean(scores_outlier)
std2 = np.std(scores_outlier)
z_scores2 = (scores_outlier - mean2) / std2

print("Standard deviation:", round(std2, 2))
print("Z-scores:", np.round(z_scores2, 2))
print("Potential outliers:",
      scores_outlier[np.abs(z_scores2) > 3])

=== Typical Data ===
Scores: [5. 6. 7. 8. 9.]
Mean: 7.0
Median: 7.0
Standard deviation: 1.41
Z-scores: [-1.41 -0.71  0.    0.71  1.41]
Potential outliers: []

=== Data With an Outlier ===
Scores: [  5.   6.   7.   8. 100.]
Mean: 25.2
Median: 7.0
Standard deviation: 37.41
Z-scores: [-0.54 -0.51 -0.49 -0.46  2.  ]
Potential outliers: []

In [8]:

import numpy as np

# Student heights (cm)
height = np.array([148, 154, 105, 108, 111, 116, 133, 149])

# 1. Minimum, maximum, and range
print("Minimum:", np.min(height))
print("Maximum:", np.max(height))
print("Range:", np.ptp(height))

# 2. 90th percentile
print("90th percentile:", np.percentile(height, 90))

# 3. Mean, median, and average
print("Mean:", np.mean(height))
print("Median:", np.median(height))
print("Average:", np.average(height))

# 4. Variance and standard deviation
print("Variance:", np.var(height))
print("Standard deviation:", np.std(height))

# 5. Interpretation
print("\nInterpretation:")
print("Heights are measured in centimeters.")
print("Range and standard deviation show the spread of heights.")
print("Variance is measured in square centimeters (cm²).")
print("The 90th percentile is a height threshold, not the maximum.")

Minimum: 105
Maximum: 154
Range: 49
90th percentile: 150.5
Mean: 128.0
Median: 124.5
Average: 128.0
Variance: 363.0
Standard deviation: 19.05255888325765

Interpretation:
Heights are measured in centimeters.
Range and standard deviation show the spread of heights.
Variance is measured in square centimeters (cm²).
The 90th percentile is a height threshold, not the maximum.

In [1]:
import numpy as np

A = np.array([[4., 2.],
              [1., 3.]])

S = np.array([[1., 2.],
              [2., 4.]])

print(round(np.linalg.det(A), 6))
print(round(np.linalg.det(S), 6))
print(np.linalg.matrix_rank(S))

10.0
0.0
1

In [2]:
import numpy as np

A = np.array([[4., 2.],
              [1., 3.]])

A_inv = np.linalg.inv(A)

print(A_inv)
print(A @ A_inv)
print(np.allclose(A @ A_inv, np.eye(2)))

[[ 0.3 -0.2]
 [-0.1  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00]]
True

In [3]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

upper = np.triu(A)
lower = np.tril(A)

print("Upper triangular:")
print(upper)

print("Lower triangular:")
print(lower)

Upper triangular:
[[1 2 3]
 [0 5 6]
 [0 0 9]]
Lower triangular:
[[1 0 0]
 [4 5 0]
 [7 8 9]]

In [4]:

import numpy as np

# Define matrices A and B
A = np.array([
    [8, 4, 1],
    [2, -4, 6],
    [5, 3, -1]
])

B = np.array([
    [6, 7, -5],
    [3, -1, -1],
    [4, 8, -2]
])

# Define matrix H
H = np.array([
    [2, 3, -3, -3],
    [-8, -1, -3, 4],
    [-6, 6, 0, -2],
    [1, 2, 9, 7]
], dtype=float)

# Task 1: Matrix arithmetic
print("A + B:\n", A + B)
print("\nA - B:\n", A - B)
print("\n3 * A:\n", 3 * A)
print("\nB - A:\n", B - A)

# Task 2: Define C and F
C = A + B
F = C / 4

print("\nC = A + B:\n", C)
print("\nF = C / 4:\n", F)
print("\nB - 2F:\n", B - 2 * F)

# Task 3: Element-wise vs matrix multiplication
print("\nA * B (element-wise):\n", A * B)
print("\nA @ B (matrix multiplication):\n", A @ B)

# Task 4: Find and verify inverse of H
H_inv = np.linalg.inv(H)

print("\nDeterminant of H:", np.linalg.det(H))
print("\nInverse of H:\n", H_inv)
print("\nH @ H_inv:\n", H @ H_inv)
print("\nInverse verified:", np.allclose(H @ H_inv, np.eye(4)))

A + B:
 [[14 11 -4]
 [ 5 -5  5]
 [ 9 11 -3]]

A - B:
 [[ 2 -3  6]
 [-1 -3  7]
 [ 1 -5  1]]

3 * A:
 [[ 24  12   3]
 [  6 -12  18]
 [ 15   9  -3]]

B - A:
 [[-2  3 -6]
 [ 1  3 -7]
 [-1  5 -1]]

C = A + B:
 [[14 11 -4]
 [ 5 -5  5]
 [ 9 11 -3]]

F = C / 4:
 [[ 3.5   2.75 -1.  ]
 [ 1.25 -1.25  1.25]
 [ 2.25  2.75 -0.75]]

B - 2F:
 [[-1.   1.5 -3. ]
 [ 0.5  1.5 -3.5]
 [-0.5  2.5 -0.5]]

A * B (element-wise):
 [[48 28 -5]
 [ 6  4 -6]
 [20 24  2]]

A @ B (matrix multiplication):
 [[ 64  60 -46]
 [ 24  66 -18]
 [ 35  24 -26]]

Determinant of H: 2256.0000000000014

Inverse of H:
 [[ 0.14893617 -0.01329787 -0.09175532  0.04521277]
 [ 0.21276596  0.03457447  0.03856383  0.08244681]
 [-0.21276596 -0.1179078   0.08643617  0.00088652]
 [ 0.19148936  0.14361702 -0.10904255  0.11170213]]

H @ H_inv:
 [[ 1.00000000e+00  5.55111512e-17  0.00000000e+00 -2.77555756e-17]
 [-1.11022302e-16  1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-8.32667268e-17 -5.55111512e-17  0.00000000e+00  1.00000000e+00]]

Inverse verified: True

In [1]:
import numpy as np

# 1. Create two 3x3 arrays
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Array A:")
print(A)

print("\nArray B:")
print(B)


# 2. Addition
print("\nAddition (A + B):")
print(A + B)


# Subtraction
print("\nSubtraction (A - B):")
print(A - B)


# Element-wise multiplication
print("\nElement-wise Multiplication (A * B):")
print(A * B)


# Element-wise division
print("\nElement-wise Division (A / B):")
print(A / B)


# 3. Total
print("\nTotal of A:")
print(A.sum())

print("\nTotal of B:")
print(B.sum())


# Row sums
print("\nRow sums of A:")
print(A.sum(axis=1))

print("\nRow sums of B:")
print(B.sum(axis=1))


# Column means
print("\nColumn means of A:")
print(A.mean(axis=0))

print("\nColumn means of B:")
print(B.mean(axis=0))


# 4. Matrix multiplication
print("\nMatrix Multiplication (A @ B):")
print(A @ B)

Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division (A / B):
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Total of A:
45

Total of B:
45

Row sums of A:
[ 6 15 24]

Row sums of B:
[24 15  6]

Column means of A:
[4. 5. 6.]

Column means of B:
[6. 5. 4.]

Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

In [2]:
import numpy as np

# 1. Create product names and revenue arrays
products = np.array(["Laptop", "Phone", "Tablet", "Headphones"])
revenues = np.array([2500, 4200, 1800, 3200])

print("Products:")
print(products)

print("\nRevenues:")
print(revenues)


# 2. Sort revenue ascending and descending

ascending = np.sort(revenues)
descending = np.sort(revenues)[::-1]

print("\nRevenue ascending:")
print(ascending)

print("\nRevenue descending:")
print(descending)


# 3. Use argsort() to rank products by revenue

# argsort gives the INDEX positions that would sort the revenues
ascending_index = np.argsort(revenues)

# Reverse the indexes for highest revenue first
descending_index = np.argsort(revenues)[::-1]

print("\nProduct ranking - highest to lowest:")

for index in descending_index:
    print(products[index], "€", revenues[index])


# 4. Report the top two products and their revenues

top_two = descending_index[:2]

print("\nTop two products:")

for index in top_two:
    print(products[index], "€", revenues[index])

Products:
['Laptop' 'Phone' 'Tablet' 'Headphones']

Revenues:
[2500 4200 1800 3200]

Revenue ascending:
[1800 2500 3200 4200]

Revenue descending:
[4200 3200 2500 1800]

Product ranking - highest to lowest:
Phone € 4200
Headphones € 3200
Laptop € 2500
Tablet € 1800

Top two products:
Phone € 4200
Headphones € 3200

In [ ]:
import numpy as np

a = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

In [3]:
print(a[[0, 2]])

[[10 11 12]
 [30 31 32]]

In [4]:
print(a[[0, 2], [1, 0]])

[11 30]

In [5]:
import numpy as np

a = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

print(a[[0, 2]])
print(a[[0, 2], [1, 0]])

[[10 11 12]
 [30 31 32]]
[11 30]

In [6]:
import numpy as np

arr1 = np.full(10, 8, dtype=complex)

print(arr1)
print(arr1.shape)

[8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]
(10,)

In [7]:
arr2 = np.arange(0, 41, 8)

print(arr2)
print(arr2.shape)

[ 0  8 16 24 32 40]
(6,)

In [8]:
arr3 = np.arange(12).reshape(3, 4)

print(arr3)
print(arr3.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)

In [9]:
second_row = arr3[1]

print(second_row)

[4 5 6 7]

In [10]:
filtered = second_row[second_row > 6]

print(filtered)

[7]

In [11]:
import numpy as np

# 1. Complex array of ten 8s
arr1 = np.full(10, 8, dtype=complex)
print("Array 1:", arr1)
print("Shape:", arr1.shape)

# 2. Values from 0 to 40 in steps of 8
arr2 = np.arange(0, 41, 8)
print("\nArray 2:", arr2)
print("Shape:", arr2.shape)

# 3. Reshape 12 values into (3, 4)
arr3 = np.arange(12).reshape(3, 4)
print("\nArray 3:")
print(arr3)
print("Shape:", arr3.shape)

# 4. Select second row and values greater than 6
second_row = arr3[1]
filtered = second_row[second_row > 6]

print("\nSecond row:", second_row)
print("Values greater than 6:", filtered)

Array 1: [8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j 8.+0.j]
Shape: (10,)

Array 2: [ 0  8 16 24 32 40]
Shape: (6,)

Array 3:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Second row: [4 5 6 7]
Values greater than 6: [7]

In [1]:
Values = [2,4,6]
print(Values*2)
import numpy as np
a=np.array([2,4,6])
print(a*2)

[2, 4, 6, 2, 4, 6]
[ 4  8 12]

In [5]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("data/product.csv")

# Display the data
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'data/product.csv'

In [7]:
import pandas as pd

df = pd.read_csv("app/data/product.csv")

print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'app/data/product.csv'

In [8]:
import os

print(os.getcwd())

/workspaces/ProgrammingForDA/app

In [10]:
import pandas as pd

df = pd.read_csv("../data/product.csv")

print(df)

    product  quantity  price
0    Laptop        10  850.0
1     Mouse        25   20.5
2  Keyboard        15   35.0

In [11]:
# Display all rows
print(df)

# Display column names
print(df.columns)

    product  quantity  price
0    Laptop        10  850.0
1     Mouse        25   20.5
2  Keyboard        15   35.0
Index(['product', 'quantity', 'price'], dtype='str')

In [12]:
print(df.head())

    product  quantity  price
0    Laptop        10  850.0
1     Mouse        25   20.5
2  Keyboard        15   35.0

In [13]:
import pandas as pd

try:
    df = pd.read_csv("products.csv")
    print(df)
    print("Columns:", df.columns.tolist())

except FileNotFoundError:
    print("Error: The CSV file was not found.")
    print("Please check the file name and file location.")

Error: The CSV file was not found.
Please check the file name and file location.

In [14]:
import pandas as pd

try:
    # Load CSV
    df = pd.read_csv("products.csv")

    # Display rows
    print("Product Data:")
    print(df)

    # Display column names
    print("\nColumn Names:")
    print(df.columns.tolist())

except FileNotFoundError:
    print("Error: products.csv was not found.")

Error: products.csv was not found.

In [15]:
import csv
from pathlib import Path

path = Path("product.csv")

rows = [
    ["product", "qty", "price"],
    ["Pen", 10, 1.20],
    ["Notebook", 3, 4.50],
    ["Folder", 2, 3.00]
]

with path.open("w", newline="", encoding="utf-8") as f:
    csv.writer(f).writerows(rows)

with path.open(newline="", encoding="utf-8") as f:
    data = list(csv.DictReader(f))

print(data)
assert len(data) == 3

[{'product': 'Pen', 'qty': '10', 'price': '1.2'}, {'product': 'Notebook', 'qty': '3', 'price': '4.5'}, {'product': 'Folder', 'qty': '2', 'price': '3.0'}]

In [1]:
df.isna

NameError: name 'df' is not defined

In [2]:
pd.info()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/people_diabetes.csv")

In [15]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [3]:
df.info()

NameError: name 'df' is not defined

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [17]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [4]:
import pandas as pd

In [18]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
df.isna

<bound method DataFrame.isna of       Name  Age Gender  Glucose  BloodPressure   BMI  Insulin  \
0    Ahmed   45      M    148.0             72  33.6      0.0
1      Ali   32      M     85.0             66  26.6     94.0
2     Sara   28      F     89.0             66  28.1     94.0
3   Fatima   52      F    183.0             64  23.3      0.0
4    Usman   41      M    137.0             40  43.1    168.0
5   Ayesha   35      F    116.0             74  34.0      0.0
6    Bilal   29      M     78.0             50  31.0     88.0
7     Hina   60      F    126.0             88  39.3      0.0
8     Omar   48      M    180.0             90  42.0    200.0
9   Zainab   31      F    100.0             72  25.5     90.0
10   Hamza   55      M    195.0             92  36.5      0.0
11  Mariam   38      F    110.0             70  32.0      NaN
12  Kashif   44      M      NaN             80  35.2    150.0
13    Sana   27      F     92.0             68  24.8     85.0
14   Imran   50      M    160.0             85  38.0    175.0
15   Nadia   42      F    105.0             75  29.5    120.0
16  Farhan   36      M     99.0             70  27.2    100.0
17   Lubna   58      F    170.0             95  45.0    300.0
18   Tariq   46      M    130.0             78  31.5    140.0
19   Sadia   33      F     88.0             60  22.5     80.0
20   Ahmed   45      M    148.0             72  33.6      0.0
21  Rashid   39      M    250.0            110  55.0    400.0

    DiabetesPedigree  Outcome
0              0.627        1
1              0.351        0
2              0.167        0
3              0.672        1
4              2.288        1
5              0.188        0
6              0.248        0
7              0.704        0
8              1.200        1
9              0.250        0
10             0.900        1
11             0.300        0
12             0.450        1
13             0.180        0
14             0.850        1
15             0.250        0
16             0.300        0
17             1.100        1
18             0.500        1
19             0.150        0
20             0.627        1
21             1.500        1  >

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
In [1]:
import pandas as pd

SyntaxError: invalid syntax (3369233704.py, line 1)

In [20]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [6]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [21]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
import pandas as pd

In [22]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [23]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [25]:
missing = pd.DataFrame({
    "Missing": df.isnull().sum(),
    "Percentage":(df.isnull().sum() / len(df)*100).round(2)
})

In [26]:
missing

             Missing  Percentage
PassengerId        0        0.00
Survived           0        0.00
Pclass             0        0.00
Name               0        0.00
Sex                0        0.00
Age              177       19.87
SibSp              0        0.00
Parch              0        0.00
Ticket             0        0.00
Fare               0        0.00
Cabin            687       77.10
Embarked           2        0.22

In [7]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import csv
from pathlib import Path
from math import log

ModuleNotFoundError: No module named 'matplotlib'

In [14]:
from pathlib import Path

In [13]:
import csv

In [12]:
import matplotlib.pyplot as plt

In [11]:
import matplotlib

In [10]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'

In [9]:
import numpy as np

In [8]:
import pandas as pd

In [8]:
df = pd.read_csv("../data/people_diabetes.csv")

In [1]:
import pandas as pd

In [9]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [3]:
df = pd.read_csv("../data/people_diabetes.csv")

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              22 non-null     str
 1   Age               22 non-null     int64
 2   Gender            22 non-null     str
 3   Glucose           21 non-null     float64
 4   BloodPressure     22 non-null     int64
 5   BMI               22 non-null     float64
 6   Insulin           21 non-null     float64
 7   DiabetesPedigree  22 non-null     float64
 8   Outcome           22 non-null     int64
dtypes: float64(4), int64(3), str(2)
memory usage: 1.7 KB

In [4]:
df

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
1,Ali,32,M,85.0,66,26.6,94.0,0.351,0
2,Sara,28,F,89.0,66,28.1,94.0,0.167,0
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
4,Usman,41,M,137.0,40,43.1,168.0,2.288,1
5,Ayesha,35,F,116.0,74,34.0,0.0,0.188,0
6,Bilal,29,M,78.0,50,31.0,88.0,0.248,0
7,Hina,60,F,126.0,88,39.3,0.0,0.704,0
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
9,Zainab,31,F,100.0,72,25.5,90.0,0.250,0
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
11,Mariam,38,F,110.0,70,32.0,NaN,0.300,0
12,Kashif,44,M,NaN,80,35.2,150.0,0.450,1
13,Sana,27,F,92.0,68,24.8,85.0,0.180,0
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
15,Nadia,42,F,105.0,75,29.5,120.0,0.250,0
16,Farhan,36,M,99.0,70,27.2,100.0,0.300,0
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
18,Tariq,46,M,130.0,78,31.5,140.0,0.500,1
19,Sadia,33,F,88.0,60,22.5,80.0,0.150,0
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1

In [11]:
df["Outcome"].value_counts()

Outcome
1    11
0    11
Name: count, dtype: int64

In [12]:
df[df["Glucose"] > 140]

,Name,Age,Gender,Glucose,BloodPressure,BMI,Insulin,DiabetesPedigree,Outcome
0,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
3,Fatima,52,F,183.0,64,23.3,0.0,0.672,1
8,Omar,48,M,180.0,90,42.0,200.0,1.200,1
10,Hamza,55,M,195.0,92,36.5,0.0,0.900,1
14,Imran,50,M,160.0,85,38.0,175.0,0.850,1
17,Lubna,58,F,170.0,95,45.0,300.0,1.100,1
20,Ahmed,45,M,148.0,72,33.6,0.0,0.627,1
21,Rashid,39,M,250.0,110,55.0,400.0,1.500,1